on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: Test get-organization-repositoriesv1
      id: hello
      uses: denis-tingajkin/get-organization-repositories@main
      with:
        github-organization: 'github'
    - name: Print results
      run: echo "${{ steps.hello.outputs.repositories }}"
